version: "3.6"

services:
    rabbit:
      image: "rabbitmq:3.8.3-management-alpine"
      container_name: go_demo_rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_ERLANG_COOKIE: "a-secret-hash"
        RABBITMQ_DEFAULT_VHOST: "demo"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"    
      networks:
        - backend      

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  db:
    driver: ${VOLUMES_DRIVER}   
  redis:
    driver: ${VOLUMES_DRIVER} 

